import { ArrowLeft, Check, ShieldCheck } from 'lucide-react'
import { Link } from 'react-router-dom'
import '../styles/product.css'

type InfoKind = 'pricing' | 'docs' | 'privacy' | 'terms'

const content: Record<InfoKind, { eyebrow: string; title: string; intro: string; sections: Array<[string, string]> }> = {
  pricing: { eyebrow: 'Private preview', title: 'No billing during the reliability preview.', intro: 'ForgeOS is currently available to invited testers without usage charges. Paid plans will begin only after browser execution, run measurement, and support expectations are stable.', sections: [['Included now', 'Create and save agents, use the visual builder, generate immutable versions, pair the development extension, and inspect synchronized runs and approvals.'], ['Fair usage', 'Preview access is intended for supervised product testing. Automated high-volume or unattended production use is not included.'], ['Future individual plan', 'Planned billing will combine a monthly workspace allowance with measured successful browser runtime, not drafts or workflow edits.'], ['Future team plan', 'Shared workspaces, member roles, approval routing, connection administration, audit retention, and higher runtime limits will be part of team plans.'], ['External costs', 'Connected model, email, calendar, publishing, telephony, and CMS providers may charge separately under their own plans.'], ['Before billing starts', 'Users will see plan limits, included usage, overage rules, cancellation terms, and a billing estimate before any paid activation.']] },
  docs: { eyebrow: 'Product guide', title: 'Build, test, and run an agent you understand.', intro: 'ForgeOS separates workflow validation, AI reasoning, and real browser actions so you always know what is happening.', sections: [['1. Choose a working template', 'Product Research and Custom Browser are the current complete starting points. Beta templates may require external services that are not enabled on every deployment.'], ['2. Complete guided setup', 'Enter the HTTPS website, outcome, changing run inputs, approval-controlled actions, and any required connections.'], ['3. Review the workflow', 'Click a node to edit its plain-language configuration. The website allowlist and blocked sensitive actions are enforced by the compiled definition.'], ['4. Check the definition', 'The Test tab validates graph order, permissions, inputs, completion criteria, and optional reasoning. It does not click the target website.'], ['5. Deploy to Chrome', 'Install or reload the ForgeOS extension, refresh the ForgeOS tab, then deploy an immutable version. Enter changing inputs inside the extension.'], ['6. Monitor and recover', 'Runs record activity and results. Approval requests wait for a person. Pause, stop, takeover, version restore, data export, and connection status remain visible.']] },
  privacy: { eyebrow: 'Data principles', title: 'Collect less. Explain more.', intro: 'ForgeOS stores only the workspace records required to build, deploy, supervise, and audit your agents.', sections: [['Account and workspace data', 'We store account identity, password credentials in salted derived form, sessions, workspace membership, settings, agents, versions, and extension pairings.'], ['Browser activity', 'The extension records run status, step titles, visible evidence summaries, results, and approval requests. Configured HTTPS domains limit where an agent may act.'], ['Sensitive information', 'Passwords, payment details, CAPTCHA, and two-factor codes are excluded from automated entry and remain under direct user control.'], ['Model processing', 'When specialist reasoning is enabled, the configured server model provider receives the goal, run inputs, and bounded visible evidence needed to create the result.'], ['Retention and control', 'Workspace owners can download a machine-readable export and permanently delete the workspace from Settings.'], ['Security contact', 'Report privacy or security concerns to studio@1forge.in. Provider and subprocessor details will be updated before broad commercial release.']] },
  terms: { eyebrow: 'Preview terms', title: 'Use ForgeOS with human supervision.', intro: 'These preview terms define the practical boundaries for testing ForgeOS before full commercial terms and service levels are introduced.', sections: [['Permitted use', 'Use ForgeOS for lawful workflows on websites and accounts you are authorized to access, while complying with each site’s terms and restrictions.'], ['Prohibited use', 'Do not bypass access controls, CAPTCHA, rate limits, purchase safeguards, security checks, or use the product for deception, abuse, credential collection, or unlawful surveillance.'], ['Human responsibility', 'Review important facts, messages, submissions, bookings, legal documents, purchases, and irreversible actions before relying on or approving them.'], ['Preview availability', 'Features may change, fail, or be withdrawn. Beta and Coming soon labels are not promises of production support or uptime.'], ['Third-party services', 'Connected websites, models, communications platforms, and other providers remain governed by their own availability, terms, and charges.'], ['Data and termination', 'You may export or delete the workspace from Settings. 1forge may suspend preview access for unsafe use, security risk, or material misuse.']] },
}

export function PublicInfoPage({ kind }: { kind: InfoKind }) {
  const page = content[kind]
  return <main className="public-info-page"><header><Link to="/"><span>F</span><strong>ForgeOS</strong></Link><nav><Link to="/#agents">Agent templates</Link><Link to="/docs">Docs</Link><Link to="/projects">Log in</Link></nav></header><section className="public-info-hero"><Link to="/"><ArrowLeft size={13} /> ForgeOS home</Link><span>{page.eyebrow}</span><h1>{page.title}</h1><p>{page.intro}</p>{kind === 'pricing' && <Link className="detail-cta" to="/playground">Open playground</Link>}</section><section className="public-info-sections">{page.sections.map(([title, text], index) => <article key={title}><span>{kind === 'privacy' || kind === 'terms' ? <ShieldCheck size={17} /> : <Check size={17} />}</span><small>{String(index + 1).padStart(2, '0')}</small><h2>{title}</h2><p>{text}</p></article>)}</section><footer><span>© {new Date().getFullYear()} 1forge · ForgeOS</span><div><Link to="/privacy">Privacy</Link><Link to="/terms">Terms</Link><Link to="/pricing">Pricing</Link></div></footer></main>
}
