import { ArrowLeft, Check, ShieldCheck } from 'lucide-react'
import { Link } from 'react-router-dom'
import '../styles/product.css'

type InfoKind = 'pricing' | 'docs' | 'privacy' | 'terms'

const content: Record<InfoKind, { eyebrow: string; title: string; intro: string; sections: Array<[string, string]> }> = {
  pricing: { eyebrow: 'Early access', title: 'Start building before pricing begins.', intro: 'ForgeOS is currently in a private product-development stage. Usage billing will be introduced only after multi-step browser runs are reliable and measurable.', sections: [['Private preview', 'Create agents, save workflows, test definitions, export versions, and use the local Chrome extension during the preview.'], ['Future usage plans', 'Plans will be based on successful agent work and runtime usage—not the number of drafts, edits, or conversations.'], ['Teams', 'Team workspaces, shared approvals, permissions, and higher runtime limits will form a separate team plan.']] },
  docs: { eyebrow: 'Product guide', title: 'Build an agent you can understand.', intro: 'Choose a template, complete guided setup, inspect the generated workflow, run a safe test, and publish a version to the browser extension.', sections: [['1. Choose a template', 'Start with Product Research, Booking, Travel, Forms, Website Research, Price Monitoring, or a Custom Browser Agent.'], ['2. Configure and test', 'Set the website, outcome, changing inputs, browser capabilities, approval rules, completion criteria, and fallback.'], ['3. Deploy', 'Publish an immutable version, download the agent definition and extension, then import the definition into the ForgeOS side panel.']] },
  privacy: { eyebrow: 'Data principles', title: 'Collect less. Explain more.', intro: 'ForgeOS is designed around workspace ownership, explicit website permissions, protected actions, and user-visible run records.', sections: [['Account data', 'We store the authenticated identity, workspace membership, agents, versions, run history, approvals, and connection status needed to provide the product.'], ['Browser activity', 'The extension acts only on configured HTTPS domains. Sensitive fields, passwords, payment details, CAPTCHA, and two-factor codes remain user-controlled.'], ['Control', 'Workspace settings provide the product surface for data export and deletion. Formal public privacy terms will be finalized before broad release.']] },
  terms: { eyebrow: 'Preview terms', title: 'Use the preview with human supervision.', intro: 'ForgeOS is an early browser-agent product. Users remain responsible for reviewing actions and complying with the terms of websites they automate.', sections: [['No unsupervised sensitive actions', 'Do not use the preview to bypass access controls, CAPTCHA, purchase safeguards, or a website’s restrictions.'], ['Review results', 'Browser layouts and content change. Verify important facts, submissions, bookings, and decisions before relying on them.'], ['Product stage', 'Features labelled Beta or Coming soon are not represented as fully supported. Formal commercial terms will be published before paid public access.']] },
}

export function PublicInfoPage({ kind }: { kind: InfoKind }) {
  const page = content[kind]
  return <main className="public-info-page"><header><Link to="/"><span>F</span><strong>ForgeOS</strong></Link><nav><Link to="/templates">Agent templates</Link><Link to="/docs">Docs</Link><Link to="/projects">Log in</Link></nav></header><section className="public-info-hero"><Link to="/"><ArrowLeft size={13} /> ForgeOS home</Link><span>{page.eyebrow}</span><h1>{page.title}</h1><p>{page.intro}</p>{kind === 'pricing' && <Link className="detail-cta" to="/templates">Start building</Link>}</section><section className="public-info-sections">{page.sections.map(([title, text], index) => <article key={title}><span>{kind === 'privacy' || kind === 'terms' ? <ShieldCheck size={17} /> : <Check size={17} />}</span><small>0{index + 1}</small><h2>{title}</h2><p>{text}</p></article>)}</section><footer><span>© {new Date().getFullYear()} 1forge · ForgeOS</span><div><Link to="/privacy">Privacy</Link><Link to="/terms">Terms</Link><Link to="/pricing">Pricing</Link></div></footer></main>
}
